import type { Study } from "./types";

/**
 * Realistic mock worklist for RSUD Dr. Saiful Anwar.
 * Names, modalities and body parts mirror the hospital's actual modality
 * inventory (Philips, Siemens, GE, Carestream, Toshiba, etc).
 */
export const MOCK_STUDIES: Study[] = [
  {
    id: "STU-2026-1001",
    patientName: "UPENN-GBM-RT-015",
    patientId: "MR-HEAD-GBM-001",
    gender: "P",
    dob: "31-05-1988",
    age: "38Y",
    modality: "MR",
    bodyPart: "Kepala",
    studyDescription: "MRI Brain - Glioblastoma Multiforme",
    studyDate: "23-09-2026",
    studyTime: "08:42",
    priority: "STAT",
    accessionNumber: "ACC-88910",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Hery, Sp.S",
    seriesCount: 1,
    imageCount: 64,
    imageSrc: "/images/mr-brain-upenn-gbm-series/instance-0001.png",
    sliceImages: Array.from({ length: 64 }, (_, i) =>
      `/images/mr-brain-upenn-gbm-series/instance-${String(i + 1).padStart(4, "0")}.png`
    ),
    imageType: "mri",
    windowWidth: 1447,
    windowCenter: 682,
    maxSlice: 64,
    pixelSpacingMm: 0.898438,
    sliceThicknessMm: 2,
    priorStudyId: "STU-2026-1001-P",
  },
  {
    id: "STU-2026-1002",
    patientName: "Yuni Astuti",
    patientId: "MR-0005678",
    gender: "P",
    dob: "02-11-1985",
    age: "41Y",
    modality: "US",
    bodyPart: "Ekstremitas Bawah",
    studyDescription: "USG Doppler Vena Femoralis",
    studyDate: "23-09-2026",
    studyTime: "08:55",
    priority: "ROUTINE",
    accessionNumber: "ACC-88921",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Maya, Sp.PD",
    seriesCount: 2,
    imageCount: 36,
    imageSrc: "/images/usg-doppler.svg",
    imageType: "usg",
    windowWidth: 220,
    windowCenter: 80,
    maxSlice: 1,
  },
  {
    id: "STU-2026-1003",
    patientName: "Supardi",
    patientId: "MR-0009012",
    gender: "L",
    dob: "20-07-1966",
    age: "60Y",
    modality: "CR",
    bodyPart: "Thorax",
    studyDescription: "X-Ray Thorax PA",
    studyDate: "23-09-2026",
    studyTime: "09:14",
    priority: "ROUTINE",
    accessionNumber: "ACC-88933",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Rina, Sp.P",
    seriesCount: 1,
    imageCount: 1,
    imageSrc: "/images/chest-xray.svg",
    imageType: "xray",
    windowWidth: 1500,
    windowCenter: 300,
    maxSlice: 1,
    priorStudyId: "STU-2026-1003-P",
  },
  {
    id: "STU-2026-1004",
    patientName: "Siti Rahma",
    patientId: "MR-0003456",
    gender: "P",
    dob: "30-01-1990",
    age: "36Y",
    modality: "CT",
    bodyPart: "Abdomen",
    studyDescription: "CT Abdomen + Kontras IV",
    studyDate: "23-09-2026",
    studyTime: "09:27",
    priority: "URGENT",
    accessionNumber: "ACC-88944",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Budi, Sp.B",
    seriesCount: 4,
    imageCount: 268,
    imageSrc: "/images/ct-abdomen.svg",
    imageType: "ct",
    windowWidth: 400,
    windowCenter: 40,
    maxSlice: 180,
  },
  {
    id: "STU-2026-1005",
    patientName: "Bambang Sutrisno",
    patientId: "MR-0007812",
    gender: "L",
    dob: "12-05-1972",
    age: "54Y",
    modality: "MR",
    bodyPart: "Kepala",
    studyDescription: "MRI Brain T1/T2/FLAIR",
    studyDate: "23-09-2026",
    studyTime: "09:48",
    priority: "ROUTINE",
    accessionNumber: "ACC-88955",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Sari, Sp.S",
    seriesCount: 8,
    imageCount: 216,
    imageSrc: "/images/mri-brain.svg",
    imageType: "mri",
    windowWidth: 2000,
    windowCenter: 400,
    maxSlice: 24,
  },
  {
    id: "STU-2026-1006",
    patientName: "Dewi Lestari",
    patientId: "MR-0001112",
    gender: "P",
    dob: "18-09-1995",
    age: "31Y",
    modality: "CR",
    bodyPart: "Manus",
    studyDescription: "X-Ray Manus Dextra AP/Lat",
    studyDate: "23-09-2026",
    studyTime: "10:02",
    priority: "ROUTINE",
    accessionNumber: "ACC-88966",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Andi, Sp.OT",
    seriesCount: 2,
    imageCount: 2,
    imageSrc: "/images/xray-hand.svg",
    imageType: "xray",
    windowWidth: 800,
    windowCenter: 200,
    maxSlice: 1,
  },
  {
    id: "STU-2026-1007",
    patientName: "Rudi Hartono",
    patientId: "MR-0004456",
    gender: "L",
    dob: "25-12-1958",
    age: "68Y",
    modality: "CT",
    bodyPart: "Kepala",
    studyDescription: "CT Kepala Non-Kontras",
    studyDate: "23-09-2026",
    studyTime: "10:19",
    priority: "STAT",
    accessionNumber: "ACC-88977",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Fajar, Sp.BS",
    seriesCount: 3,
    imageCount: 96,
    imageSrc: "/images/ct-head.svg",
    imageType: "ct",
    windowWidth: 80,
    windowCenter: 40,
    maxSlice: 120,
    priorStudyId: "STU-2026-1007-P",
  },
  {
    id: "STU-2026-1008",
    patientName: "Ani Wijayanti",
    patientId: "MR-0006678",
    gender: "P",
    dob: "09-04-1983",
    age: "43Y",
    modality: "MR",
    bodyPart: "Knee Sinistra",
    studyDescription: "MRI Knee Sinistra PD/STIR",
    studyDate: "23-09-2026",
    studyTime: "10:33",
    priority: "ROUTINE",
    accessionNumber: "ACC-88988",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Hery, Sp.OT",
    seriesCount: 5,
    imageCount: 120,
    imageSrc: "/images/mri-knee.svg",
    imageType: "mri",
    windowWidth: 1600,
    windowCenter: 400,
    maxSlice: 40,
  },
  {
    id: "STU-2026-1009",
    patientName: "Joko Prasetyo",
    patientId: "MR-0002234",
    gender: "L",
    dob: "17-08-1975",
    age: "51Y",
    modality: "CR",
    bodyPart: "Thorax",
    studyDescription: "X-Ray Thorax Lateral",
    studyDate: "22-09-2026",
    studyTime: "14:20",
    priority: "ROUTINE",
    accessionNumber: "ACC-88999",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Rina, Sp.P",
    seriesCount: 1,
    imageCount: 1,
    imageSrc: "/images/chest-lateral.svg",
    imageType: "xray",
    windowWidth: 1500,
    windowCenter: 300,
    maxSlice: 1,
    archived: true,
  },
  {
    id: "STU-2026-1010",
    patientName: "Maya Puspita",
    patientId: "MR-0008890",
    gender: "P",
    dob: "23-06-1992",
    age: "34Y",
    modality: "US",
    bodyPart: "Abdomen",
    studyDescription: "USG Abdomen Atas",
    studyDate: "22-09-2026",
    studyTime: "11:05",
    priority: "URGENT",
    accessionNumber: "ACC-89010",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Maya, Sp.PD",
    seriesCount: 2,
    imageCount: 42,
    imageSrc: "/images/usg-abdomen.svg",
    imageType: "usg",
    windowWidth: 200,
    windowCenter: 60,
    maxSlice: 1,
    archived: true,
  },
  {
    id: "STU-2026-1001-P",
    patientName: "Achmad Fauzi",
    patientId: "MR-0001234",
    gender: "L",
    dob: "14-03-1978",
    age: "48Y",
    modality: "MR",
    bodyPart: "Spine Lumbal",
    studyDescription: "MRI Lumbosacral (Prior)",
    studyDate: "10-05-2026",
    studyTime: "09:30",
    priority: "ROUTINE",
    accessionNumber: "ACC-77120",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Hery, Sp.OT",
    seriesCount: 6,
    imageCount: 144,
    imageSrc: "/images/mri-spine.svg",
    imageType: "mri",
    windowWidth: 1800,
    windowCenter: 450,
    maxSlice: 30,
    archived: true,
  },
  {
    id: "STU-2026-1003-P",
    patientName: "Supardi",
    patientId: "MR-0009012",
    gender: "L",
    dob: "20-07-1966",
    age: "60Y",
    modality: "CR",
    bodyPart: "Thorax",
    studyDescription: "X-Ray Thorax PA (Prior)",
    studyDate: "02-06-2026",
    studyTime: "10:15",
    priority: "ROUTINE",
    accessionNumber: "ACC-73011",
    institution: "RSUD Dr. Saiful Anwar",
    referringPhysician: "dr. Rina, Sp.P",
    seriesCount: 1,
    imageCount: 1,
    imageSrc: "/images/chest-xray.svg",
    imageType: "xray",
    windowWidth: 1500,
    windowCenter: 300,
    maxSlice: 1,
    archived: true,
  },
];
